import { GoogleGenAI } from "@google/genai";
import { SearchResponse } from "../types";

const getClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    // This allows the app to load even if the key is missing, 
    // but will fail gracefully when a search is attempted.
    return null;
  }
  return new GoogleGenAI({ apiKey });
};

const ai = getClient();

/**
 * Performs a search query using Gemini 2.5 Flash with Google Search Grounding.
 */
export const performSearch = async (query: string): Promise<SearchResponse> => {
  if (!ai) {
    throw new Error("API Key is missing. Please add 'API_KEY' to your Vercel Environment Variables.");
  }

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: query,
      config: {
        // Enable Google Search Grounding
        tools: [{ googleSearch: {} }],
        // Note: responseMimeType and responseSchema are NOT allowed with googleSearch
      },
    });

    const candidate = response.candidates?.[0];
    
    if (!candidate) {
      throw new Error("No response generated by the model.");
    }

    const text = response.text || "I found some information but couldn't generate a text summary.";
    const groundingMetadata = candidate.groundingMetadata;

    // Check if we actually got search results
    const hasGrounding = groundingMetadata?.groundingChunks && groundingMetadata.groundingChunks.length > 0;

    // Optional: Append a note if no web sources were found but text was generated
    const finalText = hasGrounding 
      ? text 
      : `${text}\n\n(Note: No specific web sources were cited for this response.)`;

    return {
      text: finalText,
      groundingMetadata,
    };
  } catch (error: any) {
    console.error("Gemini Search Error:", error);
    
    // enhance error message for common issues
    if (error.message?.includes("API key")) {
      throw new Error("Invalid API Key. Please check your Vercel settings.");
    }
    
    throw new Error(error.message || "An error occurred while connecting to Google Search.");
  }
};